from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from standard_user.views import update_maintenance, cancel_maintenance

urlpatterns = [
    path('', views.home, name="home"),
    path('account/login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('helpdesk', views.helpdesk_options, name='helpdesk'),
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.admin_activate, name='admin_activate'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.
         as_view(template_name='users/password_reset/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.
         as_view(template_name='users/password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/done/', auth_views.PasswordResetCompleteView.
         as_view(template_name='users/password_reset/password_reset_complete.html'), name='password_reset_complete'),
    path('inactive_users', views.inactive_users, name="inactive_users"),
    path('activate_user/<str:pk>', views.activate_user, name="activate_user"),
    path('active_users', views.active_users, name="active_users"),
    path('deactivate_user/<str:pk>', views.deactivate_user, name='deactivate_user'),
    path('admin/report/user', views.user_report, name="user_report"),
    path('admin/clients/management', views.client_options, name="client_options"),
    path('admin/client/add', views.add_client, name="add_client"),
    path('update_client/<str:pk>', views.update_client, name='update_client'),
    path('admin/report/workshop/clients', views.clients, name="clients"),
    path('admin/report/client/printers', views.client_report, name="client_report"),
    path('admin/report/maintenance', views.maintenance, name="maintenance"),
    path('admin/reports/maintenance/occurrence/detailed', views.maintenance_occurrence, name='maintenance_occurrence'),
    path('admin/reports/maintenance/occurrence/summarized', views.summarized_maintenance_occurrence,
         name='summarized_maintenance_occurrence'),
    path('admin/reports/maintenance/occurrence/prompt', views.occurrence_prompt, name='occurrence_prompt'),
    path('update_maintenance/<str:pk>', views.update_maintenance, name='update_maintenance'),
    path('cancel_maintenance/<str:pk>', views.cancel_maintenance, name='cancel_maintenance'),
    path('admin/reports/fixed/printers', views.fixed_printers, name="fixed_printers"),
    path('admin/cancelled_schedules', views.cancelled_schedules, name="cancelled_schedules"),
    path('admin/reports/fixed/not_delivered', views.fixed_undelivered_printers, name="fixed_undelivered_printers"),
    path('printer/rma/add', views.add_rma, name="add_rma"),
    path('report/workshop/printers', views.rma_requests, name="rma_requests"),
    path('update_rma/<str:pk>', views.update_rma, name='update_rma'),
    path('admin/schedule/printer', views.schedule, name="schedule"),
    path('admin/schedule/cancel', views.cancel_schedule, name="cancel_schedule"),
    path('admin/schedule/update/both', views.both_update_schedule, name="both_update_schedule"),
    path('admin/schedule/update/fixed', views.fixed_update_schedule, name="fixed_update_schedule"),
    path('schedule/update/delivery', views.delivery_update_schedule, name="delivery_update_schedule"),
    path('event', views.event, name="event"),
    path('about/', views.about, name='about'),
    path('admin/users/management', views.user_management, name="user_management"),
    path('admin/reports', views.reports, name="reports"),
    path('waybill/options', views.waybill_options, name="waybill_options"),
    path('printer/options', views.printer_options, name="printer_options"),
    path('waybill/prompt', views.waybill, name='waybill_form'),
    path('waybill/pdf', views.waybillpdf, name='waybill_pdf'),
    path('waybill/pickup/pdf', views.pickup_pdf, name='pickup_pdf'),
    path('waybill/pickup/prompt', views.pickup, name='pickup_form'),
    path('waybills/references', views.waybills, name="waybills"),
    path('user/waybills/none_uploaded', views.user_waybills, name="user_waybills"),
    path('upload_waybill/<str:pk>', views.save_waybill_from_list, name='upload'),
    path('upload/waybill/', views.save_waybill, name='upload_waybill'),
    path('upload/waybill/pickup', views.save_pickup_waybill, name='upload_pickup'),
    path('download_waybill/<str:filename>', views.download_waybill, name='download_waybill'),
    path('report/repairshop/parts', views.parts, name="parts"),
    path('report/repairshop/parts/frequently/requests', views.frequently_used_parts, name="freq_parts"),
    path('workshop/part/add', views.add_part, name="add_part"),
    path('repairshop/parts/management', views.part_management_options, name="part_options"),
    path('repairshop/part/stock/update', views.update_stock, name='update_stock'),
    path('repairshop/part/request', views.request_part, name='request_part'),
    path('repairshop/part/events', views.part_event, name='part_event'),
    path('admin/approvals/pending', views.pending_approvals, name='pending_approvals'),
    path('admin/approvals/cancelled/pending', views.cancellation_requests, name='cancellation_requests'),
    path('approvals/client/added/pending', views.added_client_requests, name='client_requests'),
    path('approvals/part/added/pending', views.added_part_requests, name='part_requests'),
    path('approve_cancellation/<str:pk>', views.approve_cancellation_request, name='approve_cancellation'),
    path('reject_cancellation/<str:pk>', views.reject_cancellation_request, name='reject_cancellation'),
    path('approve_client/<str:pk>', views.approve_added_client_request, name='approve_client'),
    path('reject_client/<str:pk>', views.reject_added_client_request, name='reject_client'),
    path('approve_part/<str:pk>', views.approve_added_part_request, name='approve_part'),
    path('reject_part/<str:pk>', views.reject_added_part_request, name='reject_part'),
    path('admin/clients/manintenance/options', views.maintenance_options, name="maintenance_options"),
    path('maintenance/agreements', views.maintenance_agreement, name='maintenance_agreement'),

    path('update_maintenance_u/<str:pk>', update_maintenance, name='update_maintenance'),
    path('cancel_maintenance_u/<str:pk>', cancel_maintenance, name='cancel_maintenance'),
]
