# Generated by Django 3.1.7 on 2021-03-31 11:23

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('printer_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rep',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='assigned_technicians',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('2', 'Paul  Denteh')], max_length=1),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fixed_by',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('2', 'Paul  Denteh')], max_length=1),
        ),
        migrations.DeleteModel(
            name='MaintenanceAgreement',
        ),
    ]
